language: node_js
node_js:
- '6.9.4'
branches:
  only:
  - dev
env:
  global:
    secure: 151479f73c2b9d76ff859b523c09f01be063fefe
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "Win-Man"
- git config --global user.email 825895587@qq.com
- sed -i'' "s~git@github.com:Win-Man/win-man.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/Win-Man/win-man.github.io.git~" _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
