language: node_js
node_js:
- '6.9.4'
branches:
  only:
  - dev
cache:
  directories:
  - node_modules
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "Win-Man"
- git config --global user.email 825895587@qq.com
- npm install -g hexo-cli
- export HEXO_DEPLOYER_REPO=https://$REPO_TOKEN@github.com/Win-Man/win-man.github.io.git
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
